### ISSUE TITLE
Running integration tests for docker fails without sudo when writing to output dir

### ISSUE THREAD

**Issue by rklonner** [dag-andersen/argocd-diff-preview#255]
I am not sure if this is a problem with my setup but I can't get the docker integration tests to run.

```
mkdir -p ./integration-test/branch-1/target-1/
cat ./output/diff.md | sed 's/\[[^][]*\]/[]/g' > ./output/diff-2.md
/bin/sh: 1: cannot create ./output/diff-2.md: Permission denied
make[3]: *** [makefile:70: run-single-test-docker] Error 2
make[3]: Leaving directory '/home/klonner/git/github/argocd-diff-preview-test-docker-integrationtest/tests'
make[2]: *** [makefile:112: run-test-all-with-docker] Error 2
make[2]: Leaving directory '/home/klonner/git/github/argocd-diff-preview-test-docker-integrationtest/tests'
make[1]: *** [makefile:134: run-test-all-docker] Error 2
make[1]: Leaving directory '/home/klonner/git/github/argocd-diff-preview-test-docker-integrationtest/tests'
make: *** [makefile:81: run-integration-tests-docker] Error 2
```

**Steps to reproduce**:
```
git clone https://github.com/dag-andersen/argocd-diff-preview.git
cd argocd-diff-preview
make run-integration-tests-docker
```

When I run the tests with `sudo make run-integration-tests-docker` it works.

I assume it is because the output dir is created within the container when it does not exist yet.
When I run the [demo ](https://dag-andersen.github.io/argocd-diff-preview/demo/) successfully it leaves me with this permissions.

```
drwxr-xr-x 10 klonner klonner 4096 Oct 26 21:02 base-branch
drwxr-xr-x  4 root    root    4096 Oct 26 21:04 output
drwxr-xr-x 10 klonner klonner 4096 Oct 26 21:02 target-branch
```

Creating the `tests/output` folder before executing the tests does not help because this folder is removed after every integration test (which makes sense)

```
rm -rf base-branch || true
rm -rf target-branch || true
rm -rf output || true
rm -rf temp || true
```

Attached you can find the full output of a run.

[integration-tests-docker-error-messages.log](https://github.com/user-attachments/files/23153401/integration-tests-docker-error-messages.log)

Do I need to consider something before executing the tests?
If not, do you have a hint what could be the issue with my environment.

**Comment by dag-andersen** [comment]
> Do I need to consider something before executing the tests?

@rklonner I don't think so 😬 

If I run  
```
git clone https://github.com/dag-andersen/argocd-diff-preview.git
cd argocd-diff-preview
make run-integration-tests-docker
```
it works on the first try. I’ve tested it on multiple of my computers.  

I’m not an expert in file permissions, but here are my permissions after running the integration test. I don’t know if that helps in any way 🤷🏻 

<img width="497" height="422" alt="Image" src="https://github.com/user-attachments/assets/0e613307-d2a9-41c7-b075-7b394639f579" />

**Comment by rklonner** [comment]
Thanks for the fast confirmation. 👍 
Then I will further check my docker setup and get the permissions right.

**Comment by rklonner** [comment]
Sorry to bother you with my docker issues but I would really be interested in running the integration tests for this project - please tell me when this goes too far, I totally understand that. Must be something obvious that I do not see currently.

I am running a fresh installation of ubuntu 24.04 in WSL2 in Windows but I know the following behaviour also from other docker installations and do not get the point how it writes out the files as your user.

By default, the user within a container is root [Docker docs](https://docs.docker.com/engine/containers/run/#user)

To check this with the image of this project I modified the argocd-diff-preview Dockerfile to point to the static debian `debug` tag which provides shell access
```
FROM gcr.io/distroless/static-debian12:debug AS final
docker build -t argocd-diff-preview-analyze-permissions .
docker run -it --entrypoint=sh argocd-diff-preview-analyze-permissions
# within the container
/ # whoami
root
```

Would be interested if this is also root for you or already your user.

If I would like that the files created by the container belong to my user I would provide my uid/gui when starting the container
If you want to start it as your own user, you would do e.g.
`docker run --user=$(id -u):$(id -g) ...`

So I could try to run the Argocd diff preview demo like

```
docker run --user=$(id -u):$(id -g) 
--network host    
-v /var/run/docker.sock:/var/run/docker.sock    
-v $(pwd)/output:/output    
-v $(pwd)/base-branch:/base-branch   
-v $(pwd)/target-branch:/target-branch    
-e TARGET_BRANCH=helm-example-3    
-e REPO=dag-andersen/argocd-diff-preview   
dagandersen/argocd-diff-preview:v0.1.19
```

but then I do not have the right to write files within the container as it is not aware of my uid or any groups I have on my host machine

```
❌ failed to delete existing cluster: Deleting cluster "argocd-diff-preview" ...
failed to update kubeconfig: failed to lock config file: mkdir /.kube: permission denied
ERROR: failed to delete cluster "argocd-diff-preview": failed to lock config file: mkdir /.kube: permission denied
```

I guess further down there would be additional issues regarding dind as I would need permissons on the docker socket `/var/run/docker.sock` which I have over the docker group on my host machine but not within the container, so it actually needs to run as root.

**Comment by dag-andersen** [comment]
@rklonner 
I haven’t tried running it on Windows WSL. I only have macOS computers, so I can’t verify if I get the same result on Windows.

---

Mine is also running as root so i don't think that is the issue
```
FROM gcr.io/distroless/static-debian12:debug AS final
docker build -t argocd-diff-preview-analyze-permissions .
docker run -it --entrypoint=sh argocd-diff-preview-analyze-permissions
/ # whoami
root
```

---

```
ERROR: failed to delete cluster "argocd-diff-preview": failed to lock config file: mkdir /.kube: permission denied
```
i rarely see this, but when it happens i just delete the whole `~/.kube/` dir and it usually works again 🤷🏻

**Comment by rklonner** [comment]
@dag-andersen : I did some reading about how docker handles file ownership - "Mac vs Linux"

I am pretty sure [this article](https://www.fullstaq.com/knowledge-hub/blogs/docker-and-the-host-filesystem-owner-matching-problem) summarizes the problem we see here:

> For example: on a Linux machine (not on macOS; see below), let’s run a root container which writes a file on the host:

`docker run --rm -v "$(pwd):/host" busybox touch /host/foo.txt`

> This file is owned by root, and we can’t modify it

:

```
$ ls -l foo.txt
-rw-r--r-- 1 root root 0 Jan 17 10:36 foo.txt
$ echo hi > foo.txt
-bash: foo.txt: Permission denied
```

And

> Only on Linux, not on macOS
> 
> These problems are only applicable when using Docker on Linux. macOS users don’t experience these problems at all, because Docker for Mac actually runs a Linux VM, and inside that VM it mounts host filesystems into the container as a network volume. It ensures that:
> 
> Inside the container, all mounted files look as if they’re owned by the container user.
> 
> On the host, all files written by the container become owned by the host user.
> 
> But the fact that macOS users don’t get this problem, is in itself a problem. It means that when someone creates a container-as-OS-app on macOS, and hands it over to a Linux user, then that app may not work because of the permission problems described above.


So starting the container like

`docker run --user=$(id -u):$(id -g) ...
`

And providing the needed permissions inside the container for the host user could be a potential solution.

I try to create an example for further discussion.

**Comment by dag-andersen** [comment]
Hi @rklonner

I am not sure if you ever managed to get the integration tests working locally :/
Unfortunately, I have pretty poor conditions for testing user permissions on Windows WSL myself.

That said, I have updated the docs with instructions on [how to run the tool using GitHub Codespaces](https://github.com/dag-andersen/argocd-diff-preview/blob/main/CONTRIBUTING.md#github-codespaces-simplest-way-to-get-started). Based on my limited testing, it seems to work quite well, and I am able to run all integration tests there.

Do you think that would be a good enough developer experience?

I am not sure if you have any experience with Dev Containers, but if the GitHub Codespaces experience is not good enough, maybe you could try running the Dev Container locally on your Windows machine using [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers).

**Comment by rklonner** [comment]
Hi @dag-andersen ,

unfortunately I was not able to fully solve the problem. 

I tested the docker integration tests in a github codespace as you suggested and it works. Here it works because one is working as root user.

<img width="681" height="54" alt="Image" src="https://github.com/user-attachments/assets/ea033c50-3f54-4764-a58a-24b9ce83cd3d" />

It does not fully solve the original problem but it provides a nice remote space where it will work for everyone.

The last thing I looked at was [fixuid](https://github.com/boxboat/fixuid) - it would make it possible to use a provided uid/gid in the docker call to change the uid/gid at runtime so that the files written to disc (e.g. diff.md) belong to a specific user on the host (in our case my personal user). According to the number of stars I think it addresses a problem :) However it should not be used in production containers and is therefore not ideal to use it for the integration tests.

Maybe one has to state in general for a tool like argocd-diff-preview that if it is used with docker on the local machine that it should be used with a managed docker setup like Docker for Windows/Mac which are handling the permissions for files written to the host for the end-user. If you just run it once under Linux with "plain" docker you do not notice an issue immediately, just when you want to cleanup or run the integration tests in that setup it will fail to cleanup the files that belong to root. I am just missing the right terms now to describe it, then it could be just a note in the contribution guideline to watch out for that.

In the case you also do not have a suggestion how to describe that problem we can close that issue.

**Comment by dag-andersen** [comment]
Alright! Good to know that you _can_ run the integration tests when using GitHub Workflows :)

For now, I think it is good enough to just link to this issue, so people do not end up spending a long time debugging the file permission issue :) [[pr]](https://github.com/dag-andersen/argocd-diff-preview/pull/290)
